-- 코드를 입력하세요
SELECT YEAR(a.SALES_DATE) as YEAR, MONTH(a.SALES_DATE) as MONTH, b.GENDER, COUNT(DISTINCT a.USER_ID) as USERS
    FROM ONLINE_SALE as a
    JOIN USER_INFO as b
    ON a.USER_ID = b.USER_ID AND b.GENDER IS NOT NULL
    # WHERE b.GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, GENDER
    ORDER BY YEAR, MONTH, GENDER