-- 코드를 입력하세요
SELECT a.FLAVOR FROM FIRST_HALF as a
JOIN (SELECT SUM(c.TOTAL_ORDER) + SUM(b.TOTAL_ORDER) as TT, c.FLAVOR FROM JULY as c
      JOIN FIRST_HALF as b
      ON c.FLAVOR = b.FLAVOR
      GROUP BY c.FLAVOR) as d
ON a.FLAVOR = d.FLAVOR
ORDER BY d.TT DESC
LIMIT 3