-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, SUM(a.PRICE * b.SALES_AMOUNT) as SALES FROM PRODUCT as a
JOIN OFFLINE_SALE as b 
ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE