-- 코드를 입력하세요
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(b.AMOUNT * a.PRICE) as TOTAL_SALES FROM FOOD_PRODUCT as a
JOIN FOOD_ORDER as b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE DATE_FORMAT(b.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID